#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt and release
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h

      - name: Update feeds
        run: |
          # sed -i '11s/\"#src-git\"/\"src-git\"/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          
          cat >> .config <<EOF
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_phicomm_k2p=y

          CONFIG_PACKAGE_luci-app-accesscontrol=y
          CONFIG_PACKAGE_luci-app-autoreboot=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-flowoffload=y
          CONFIG_PACKAGE_luci-app-mtwifi=y
          CONFIG_PACKAGE_luci-app-ramfree=y
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-wol=y
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          
          CONFIG_PACKAGE_ipv6helper=y

          #### plugin ####
          CONFIG_PACKAGE_luci-app-ddns=y
          # CONFIG_PACKAGE_luci-app-dnsforwarder is not set
          CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
          
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_PACKAGE_luci-i18n-filetransfer-zh-cn=y
          
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-i18n-unblockmusic-zh-cn=y
          
          CONFIG_PACKAGE_luci-app-vsftpd=y
          CONFIG_PACKAGE_luci-i18n-vsftpd-zh-cn=y
          CONFIG_PACKAGE_vsftpd-alt=y
          CONFIG_VSFTPD_USE_UCI_SCRIPTS=y
          
          #### ssr ####
          CONFIG_FEED_helloworld=y
          CONFIG_PACKAGE_resolveip=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_luci-lib-fs=y
          CONFIG_PACKAGE_libmbedtls=y
          # CONFIG_LIBMBEDTLS_DEBUG_C is not set
          CONFIG_PACKAGE_libev=y
          CONFIG_PACKAGE_libmnl=y
          CONFIG_PACKAGE_libnet-1.2.x=y
          CONFIG_PACKAGE_libpcap=y
          # CONFIG_PCAP_HAS_USB is not set
          # CONFIG_PCAP_HAS_NETFILTER is not set
          CONFIG_PACKAGE_libsodium=y
          CONFIG_PACKAGE_iptables-mod-tproxy=y
          CONFIG_PACKAGE_dns2socks=y

          CONFIG_PACKAGE_v2ray=y
          CONFIG_V2RAY_COMPRESS_GOPROXY=y
          # CONFIG_V2RAY_JSON_V2CTL is not set
          CONFIG_V2RAY_JSON_INTERNAL=y
          # CONFIG_V2RAY_JSON_NONE is not set
          CONFIG_V2RAY_EXCLUDE_V2CTL=y
          CONFIG_V2RAY_EXCLUDE_ASSETS=y
          CONFIG_V2RAY_COMPRESS_UPX=y
          CONFIG_V2RAY_DISABLE_NONE=y
          # CONFIG_V2RAY_DISABLE_CUSTOM is not set
          CONFIG_PACKAGE_v2ray-plugin=y
          
          CONFIG_PACKAGE_shadowsocks-libev-config=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_shadowsocksr-libev-alt=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_simple-obfs=y
          # CONFIG_SIMPLE_OBFS_STATIC_LINK is not set
          
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_libipset=y
          CONFIG_PACKAGE_microsocks=y
          CONFIG_PACKAGE_tcpping=y
          
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin is not set
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2 is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server is not set

          # CONFIG_PACKAGE_luci-i18n-ddns-bg is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-ca is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-cs is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-de is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-el is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-en is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-es is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-fr is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-he is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-hi is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-hu is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-it is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-ja is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-ko is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-mr is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-ms is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-no is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-pl is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-pt is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-pt-br is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-ro is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-ru is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-sk is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-sv is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-tr is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-uk is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-vi is not set
          CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
          # CONFIG_PACKAGE_luci-i18n-ddns-zh-tw is not set
          
          CONFIG_PACKAGE_coreutils=y
          # CONFIG_PACKAGE_coreutils-b2sum is not set
          # CONFIG_PACKAGE_coreutils-base32 is not set
          CONFIG_PACKAGE_coreutils-base64=y
          # CONFIG_PACKAGE_coreutils-basename is not set
          # CONFIG_PACKAGE_coreutils-basenc is not set
          # CONFIG_PACKAGE_coreutils-cat is not set
          # CONFIG_PACKAGE_coreutils-chcon is not set
          # CONFIG_PACKAGE_coreutils-chgrp is not set
          # CONFIG_PACKAGE_coreutils-chmod is not set
          # CONFIG_PACKAGE_coreutils-chown is not set
          # CONFIG_PACKAGE_coreutils-chroot is not set
          # CONFIG_PACKAGE_coreutils-cksum is not set
          # CONFIG_PACKAGE_coreutils-comm is not set
          # CONFIG_PACKAGE_coreutils-cp is not set
          # CONFIG_PACKAGE_coreutils-csplit is not set
          # CONFIG_PACKAGE_coreutils-cut is not set
          # CONFIG_PACKAGE_coreutils-date is not set
          # CONFIG_PACKAGE_coreutils-dd is not set
          # CONFIG_PACKAGE_coreutils-df is not set
          # CONFIG_PACKAGE_coreutils-dir is not set
          # CONFIG_PACKAGE_coreutils-dircolors is not set
          # CONFIG_PACKAGE_coreutils-dirname is not set
          # CONFIG_PACKAGE_coreutils-du is not set
          # CONFIG_PACKAGE_coreutils-echo is not set
          # CONFIG_PACKAGE_coreutils-env is not set
          # CONFIG_PACKAGE_coreutils-expand is not set
          # CONFIG_PACKAGE_coreutils-expr is not set
          # CONFIG_PACKAGE_coreutils-factor is not set
          # CONFIG_PACKAGE_coreutils-false is not set
          # CONFIG_PACKAGE_coreutils-fmt is not set
          # CONFIG_PACKAGE_coreutils-fold is not set
          # CONFIG_PACKAGE_coreutils-groups is not set
          # CONFIG_PACKAGE_coreutils-head is not set
          # CONFIG_PACKAGE_coreutils-hostid is not set
          # CONFIG_PACKAGE_coreutils-id is not set
          # CONFIG_PACKAGE_coreutils-install is not set
          # CONFIG_PACKAGE_coreutils-join is not set
          # CONFIG_PACKAGE_coreutils-kill is not set
          # CONFIG_PACKAGE_coreutils-link is not set
          # CONFIG_PACKAGE_coreutils-ln is not set
          # CONFIG_PACKAGE_coreutils-logname is not set
          # CONFIG_PACKAGE_coreutils-ls is not set
          # CONFIG_PACKAGE_coreutils-md5sum is not set
          # CONFIG_PACKAGE_coreutils-mkdir is not set
          # CONFIG_PACKAGE_coreutils-mkfifo is not set
          # CONFIG_PACKAGE_coreutils-mknod is not set
          # CONFIG_PACKAGE_coreutils-mktemp is not set
          # CONFIG_PACKAGE_coreutils-mv is not set
          # CONFIG_PACKAGE_coreutils-nice is not set
          # CONFIG_PACKAGE_coreutils-nl is not set
          # CONFIG_PACKAGE_coreutils-nohup is not set
          # CONFIG_PACKAGE_coreutils-nproc is not set
          # CONFIG_PACKAGE_coreutils-numfmt is not set
          # CONFIG_PACKAGE_coreutils-od is not set
          # CONFIG_PACKAGE_coreutils-paste is not set
          # CONFIG_PACKAGE_coreutils-pathchk is not set
          # CONFIG_PACKAGE_coreutils-pinky is not set
          # CONFIG_PACKAGE_coreutils-pr is not set
          # CONFIG_PACKAGE_coreutils-printenv is not set
          # CONFIG_PACKAGE_coreutils-printf is not set
          # CONFIG_PACKAGE_coreutils-ptx is not set
          # CONFIG_PACKAGE_coreutils-pwd is not set
          # CONFIG_PACKAGE_coreutils-readlink is not set
          # CONFIG_PACKAGE_coreutils-realpath is not set
          # CONFIG_PACKAGE_coreutils-rm is not set
          # CONFIG_PACKAGE_coreutils-rmdir is not set
          # CONFIG_PACKAGE_coreutils-runcon is not set
          # CONFIG_PACKAGE_coreutils-seq is not set
          # CONFIG_PACKAGE_coreutils-sha1sum is not set
          # CONFIG_PACKAGE_coreutils-sha224sum is not set
          # CONFIG_PACKAGE_coreutils-sha256sum is not set
          # CONFIG_PACKAGE_coreutils-sha384sum is not set
          # CONFIG_PACKAGE_coreutils-sha512sum is not set
          # CONFIG_PACKAGE_coreutils-shred is not set
          # CONFIG_PACKAGE_coreutils-shuf is not set
          # CONFIG_PACKAGE_coreutils-sleep is not set
          # CONFIG_PACKAGE_coreutils-sort is not set
          # CONFIG_PACKAGE_coreutils-split is not set
          # CONFIG_PACKAGE_coreutils-stat is not set
          # CONFIG_PACKAGE_coreutils-stdbuf is not set
          # CONFIG_PACKAGE_coreutils-stty is not set
          # CONFIG_PACKAGE_coreutils-sum is not set
          # CONFIG_PACKAGE_coreutils-sync is not set
          # CONFIG_PACKAGE_coreutils-tac is not set
          # CONFIG_PACKAGE_coreutils-tail is not set
          # CONFIG_PACKAGE_coreutils-tee is not set
          # CONFIG_PACKAGE_coreutils-test is not set
          # CONFIG_PACKAGE_coreutils-timeout is not set
          # CONFIG_PACKAGE_coreutils-touch is not set
          # CONFIG_PACKAGE_coreutils-tr is not set
          # CONFIG_PACKAGE_coreutils-true is not set
          # CONFIG_PACKAGE_coreutils-truncate is not set
          # CONFIG_PACKAGE_coreutils-tsort is not set
          # CONFIG_PACKAGE_coreutils-tty is not set
          # CONFIG_PACKAGE_coreutils-uname is not set
          # CONFIG_PACKAGE_coreutils-unexpand is not set
          # CONFIG_PACKAGE_coreutils-uniq is not set
          # CONFIG_PACKAGE_coreutils-unlink is not set
          # CONFIG_PACKAGE_coreutils-uptime is not set
          # CONFIG_PACKAGE_coreutils-users is not set
          # CONFIG_PACKAGE_coreutils-vdir is not set
          # CONFIG_PACKAGE_coreutils-wc is not set
          # CONFIG_PACKAGE_coreutils-who is not set
          # CONFIG_PACKAGE_coreutils-whoami is not set
          # CONFIG_PACKAGE_coreutils-yes is not set
          # CONFIG_PACKAGE_flent-tools is not set
       
          EOF
          
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
